services:
  app:
    image: ghcr.io/yasirmaxstyle/fgo24-be-tickitz:latest
    networks:
      - netapp
    ports:
      - 9503:9503
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  postgres:
    image: postgres
    env_file:
      - .env
    volumes:
      - data_postgres:/var/lib/postgresql/data
    networks:
      - netapp
    restart: unless-stopped

  redis:
    image: redis
    volumes:
      - data_redis:/data
    networks:
      - netapp
    restart: unless-stopped

volumes:
  data_postgres:
  data_redis:


networks:
  netapp:
