name: Push Image to GHCR
run-name: release Image GHCR

on:
  push:
    branches:
      - master
    
jobs:
  push-image-to-ghcr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest

      
      - name: Copy migrations to VPS
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          port: 9501
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "migrations"
          target: "/home/yasir/be-noir"
        
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 9501
          script: |
            cd /home/yasir/be-noir
            docker pull ghcr.io/yasirmaxstyle/fgo24-be-tickitz:latest
            docker compose up -d postgres redis
            docker run --rm \
              --network be-noir_netapp \
              -v "$PWD/migrations:/migrations" \
              migrate/migrate \
              -path=/migrations \
              -database "postgres://postgres:1@postgres:5432/noir?sslmode=disable" \
              up
            docker compose up -d --build app

